web/goalkeeper/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email


class RegisterForm(FlaskForm):
    username = StringField('Email', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])

web/goalkeeper/friends/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email


class RegisterForm(FlaskForm):
    username = StringField('Email', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])

web/goalkeeper/__init__.py
from flask import Flask, render_template, flash
from goalkeeper.accounts.forms import LoginForm
from flask_login import LoginManager
from flask_nav import Nav

from goalkeeper.models import db, User
from . import config

login_manager = LoginManager()
nav = Nav()
app = Flask(__name__)

def create_app(test_config=None):
    app.config['SQLALCHEMY_DATABASE_URI'] = config.DATABASE_CONNECTION_URI
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SECRET_KEY'] = 'super secret key'

    # if test_config is None:
    #     # load the instance config, if it exists, when not testing
    #     app.config.from_pyfile("config.py", silent=True)
    # else:
    #     # load the test config if passed in
    #     app.config.update(test_config)

    app.app_context().push()
    db.init_app(app)

    # Register the blueprints
    from goalkeeper.accounts.routes import accounts
    from goalkeeper.goals.routes import goals
    from goalkeeper.friends.routes import friends
    from goalkeeper.notifications.routes import notifications
    from goalkeeper.forum.routes import forum
    from goalkeeper.feed.routes import feed

    app.register_blueprint(accounts)
    app.register_blueprint(goals)
    app.register_blueprint(friends)
    app.register_blueprint(notifications)
    app.register_blueprint(forum)
    app.register_blueprint(feed)

    # Initialize the user loader
    @login_manager.user_loader
    def load_user(user_id):
        #flash(user_id)
        return User.query.get(user_id)

    # Initialize login manager
    login_manager.login_view = 'accounts.login'
    login_manager.init_app(app)

    # Initialize the navigation bar
    from goalkeeper.navigation import account_nav
    nav.init_app(app)

    # Login page will be the home page
    @app.route('/')
    def index():
        form = LoginForm()
        return render_template("login.html", form=form)

    return app

if __name__ == "__main__":
    app.run(threaded=True)

web/goalkeeper/accounts/__init__.py
# from goalkeeper.app import User
# from goalkeeper.app import login_manager
#
# # Initialize the login manager
# @login_manager.user_loader
# def load_user(user_id):
#     return User.query.get(user_id)

web/goalkeeper/accounts/routes.py
from flask import Blueprint, flash, url_for, redirect, render_template
from flask_login import login_user, login_required, current_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash
from goalkeeper.accounts.forms import LoginForm, RegisterForm
from goalkeeper.models import db, User, Goal
from flask import request
from goalkeeper.goals.forms import GoalForm
from sys import stderr

accounts = Blueprint("accounts", __name__, url_prefix="/accounts")


@accounts.route('/home', methods=['GET'])
@login_required
def home():
    # Home Page only needs to display current goals
    result = Goal.query.filter(Goal.user_email == current_user.email).all()

    storage = []
    for goal in result:
        if goal.completion == False:
            storage.append(goal)
    return render_template('home.html', results=storage)

@accounts.route('/completed_goals', methods=['GET'])
@login_required
def completed_goals():
    result = Goal.query.filter(Goal.user_email == current_user.email).all()

    storage = []
    for goal in result:
        if goal.completion == True:
            storage.append(goal)
    return render_template('completed_goals.html', results=storage)


@accounts.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            # flash(user.id + " " + user.username + " " + user.email)
            if user and check_password_hash(user.password, form.password.data):
                login_user(user, remember=True)
                flash('Logged in successfully.', 'success')
                # Retrieve lists of goals in account
                return redirect(url_for("accounts.home"))

            flash('Invalid login.', 'danger')
            return redirect(url_for("accounts.login"))
    else:
        return render_template("login.html", form=form)
#
#
@accounts.route("/logout", methods=["GET"])
@login_required
def logout():
    """Logout the current user."""
    logout_user()
    form = LoginForm()
    return render_template("login.html", form=form)


@accounts.route("/register", methods=("GET", "POST"))
def register():
    """Register a new user.
    Validates that the username is not already taken. Hashes the
    password for security.
    """
    form = RegisterForm()
    if request.method == "POST":
        if form.validate_on_submit():
            user = User.query.filter(User.email == form.email.data).first()
            if user:
                flash('Email already taken.', 'info')
                return render_template("register.html", form=form)

            user = User(
                username=form.username.data,
                email=form.email.data,
                password=generate_password_hash(form.password.data)
            )
            db.session.add(user)
            db.session.commit()
            flash('New account created successfully.', 'success')
            return render_template("login.html", form=LoginForm())
    else:
        flash("Register Here!", "success")

    return render_template("register.html", form=form)

@accounts.route('/calendar', methods=['GET'])
@login_required
def view_calendar():
    form = GoalForm()
    return render_template("calendar.html", form=form)

web/goalkeeper/feed/routes.py
from flask import Blueprint, flash, url_for, redirect, render_template
from flask_login import login_user, login_required, current_user, logout_user
from goalkeeper.models import db, User, Goal, Friend, Feed
from flask import request
from goalkeeper.goals.forms import GoalForm
from datetime import datetime
from sys import stderr

# Feed will have news when someone becomes friends with your friend or
# when a friend creates a new goal or completes a goal.

feed = Blueprint("feed", __name__, url_prefix="/feed")

@feed.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    # Find friends of the user
    friend_query1 = Friend.query.filter(Friend.user1_email == current_user.email).with_entities(
    Friend.user2_email.label('user1_email'))
    friend_query2 = Friend.query.filter(Friend.user2_email == current_user.email).with_entities(Friend.user1_email)
    intersection = friend_query1.intersect(friend_query2)
    friends_of_user = User.query.filter(User.email.in_(intersection)).with_entities(User.email)

    # Query the goals completed and created for each friend as well as friend requests
    result = Feed.query.filter(Feed.author.in_(friends_of_user)).order_by(Feed.date_posted.desc())

    return render_template("feed.html", results=result)

web/goalkeeper/friends/routes.py
from flask import Blueprint, flash, url_for, redirect, render_template
from flask_login import login_user, login_required, current_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash
from goalkeeper.accounts.forms import LoginForm, RegisterForm
from goalkeeper.models import db, User, Friend, Goal, Notification, Feed
from flask import request
from goalkeeper.goals.forms import GoalForm
from sys import stderr
from sqlalchemy import or_
from sqlalchemy.orm import aliased

friends = Blueprint("friends", __name__, url_prefix="/friends")


@friends.route('/list_friends', methods=['GET'])
@login_required
def list_friends():
    # Return list of all friends and people on the platform
    friend_query1 = Friend.query.filter(Friend.user1_email == current_user.email).with_entities(Friend.user2_email.label('user1_email'))
    friend_query2 = Friend.query.filter(Friend.user2_email == current_user.email).with_entities(Friend.user1_email)
    intersection = friend_query1.intersect(friend_query2)
    union = friend_query1.union_all(friend_query2)
    pending_set_receive = friend_query2.except_(intersection)
    pending_set_sent = friend_query1.except_(intersection)
    friends_of_user = User.query.filter(User.email.in_(intersection)).all()
    not_friends_of_user = User.query.filter(~User.email.in_(union)).filter(User.email != current_user.email).all()
    receive = User.query.filter(User.email.in_(pending_set_receive)).all()
    sent = User.query.filter(User.email.in_(pending_set_sent)).all()
    return render_template("friends_list.html", friends=friends_of_user, find_friends=not_friends_of_user, pending_receive=receive, pending_sent=sent)


@friends.route('/add_friend/<friendemail>', methods=['GET'])
@login_required
def add_friend(friendemail):
    # Add Friend to a table
    friend = Friend(
        user1_email=current_user.email,
        user2_email=friendemail,
    )

    # Check if user is accepting friend request
    # We know that if the current user email and friend email are
    # already in the table, then we know that they became friends.
    if Friend.query.filter(Friend.user2_email == current_user.email).filter(Friend.user1_email == friendemail).first():
        post1 = Feed(
            title=friendemail + ' and ' + current_user.email + ' became friends!',
            author=current_user.email
        )

        post2 = Feed(
            title=friendemail + ' and ' + current_user.email + ' became friends!',
            author=friendemail
        )
        db.session.add(post1)
        db.session.add(post2)

    db.session.add(friend)
    if len(Friend.query.filter(Friend.user1_email == friendemail).all()) > 0:
        notification = Notification(
            user_email=friendemail,
            description=current_user.username + " accepted your friend request!",
            link=url_for('friends.list_friends')
        )
        db.session.add(notification)
    else:
        notification = Notification(
            user_email=friendemail,
            description=current_user.username + " sent you a friend request!",
            link=url_for('friends.list_friends')
        )
        db.session.add(notification)
    db.session.commit()

    return redirect(url_for('friends.list_friends'))

@friends.route('/view_profile/<friendemail>', methods=['GET'])
@login_required
def view_profile(friendemail):
    # Return Profile of User
    goals_of_user = Goal.query.filter(Goal.user_email == friendemail)
    complete_goals_of_user = goals_of_user.filter(Goal.completion == True).filter(Goal.private_goal == False).all()
    uncomplete_goals_of_user = goals_of_user.filter(Goal.completion == False).filter(Goal.private_goal == False).all()
    user = User.query.filter(User.email == friendemail).first()
    return render_template('profile.html', friend_user=user, completed_goals=complete_goals_of_user, uncompleted_goals=uncomplete_goals_of_user)

web/goalkeeper/goals/routes.py
from flask import Blueprint, flash, url_for, redirect, render_template
from flask_login import login_user, login_required, current_user, logout_user
from goalkeeper.models import db, User, Goal, Tag, Friend, Notification, Feed, get_friends
from flask import request
from goalkeeper.goals.forms import GoalForm
from datetime import datetime
from sys import stderr
from goalkeeper.categories.tags import is_tag_str, get_tags


goals = Blueprint("goals", __name__, url_prefix="/goals")

@goals.route('/<goalid>', methods=['GET', 'POST'])
@login_required
def goal(goalid):
    # Find the goal in the Goal table
    result = Goal.query.filter(Goal.id == goalid).first()

    if request.method == "POST":
        result.completion = True
        if not result.private_goal:
            post = Feed(
                title= 'Goal Completed: ' + result.description,
                author=current_user.email
            )
            db.session.add(post)
            for friend in get_friends(current_user.email):
                notification = Notification(
                    user_email=friend.email,
                    description=friend.username + " completed their goal: " + result.title,
                    link=url_for('goals.goal', goalid=result.id)
                )
                db.session.add(notification)
        db.session.commit()
        return redirect(url_for("accounts.home"))


    return render_template("goal.html", currentgoal=result, useremail=current_user.email)

@goals.route('/add_goal', methods=['GET', 'POST'])
@login_required
def add_goal():
    if request.method == "GET":
        # We are retrieving the webpage here
        form = GoalForm()
        return render_template("add_goal.html", form=form)
    else:
        # We are adding goals here
        form = GoalForm()

        goal = Goal(
            user_email=current_user.email,
            title=form.title.data,
            description=form.description.data,
            tags=(form.tags.data if is_tag_str(form.tags.data) else ''),
            private_goal=(form.private_goal is not None and form.private_goal.data)
        )

        # Register a tag
        tags = Tag.query.all()
        for index,tag in enumerate(tags): tags[index] = tag.text.lower()
        for tag in get_tags(form.tags.data):
            # If a tag is not in the tag database, add it
            if not tag.lower() in tags:
                tag = Tag(text=tag)
                db.session.add(tag)

        if form.due_date is not None:
            print(form.due_date)
            if form.due_date.data is not None:
                print(form.due_date.data)
                try:
                    x = float(form.due_date.data) / 1000.0
                    goal.due_date = datetime.fromtimestamp(x)
                except ValueError:
                    pass

        # We are adding to the news feed here
        post = Feed(
            title='New Goal Created: ' + form.description.data,
            author=current_user.email
        )

        db.session.add(goal)
        db.session.add(post)
        friends = get_friends(current_user.email)
        if not goal.private_goal:
            for friend in friends:
                notification = Notification(
                    user_email=friend.email,
                    description=friend.username + " posted a new goal: " + goal.title,
                    link=url_for('goals.goal', goalid=goal.id)
                )
                db.session.add(notification)
        db.session.commit()
        return redirect(url_for("accounts.home"))


# @goals.route('/edit_goal', methods=['GET', 'POST'])
# def edit_goal():
#     if request.method == "GET":
#         # We are retrieving the webpage here
#         form = GoalForm()
#         return render_template("add_goal.html", form=form)
#     else:
#         # We are adding goals here
#         form = GoalForm()
#         goal = Goal(
#             user_email=current_user.email,
#             title=form.title.data,
#             description=form.description.data,
#         )
#         db.session.add(goal)
#         db.session.commit()
#         return redirect(url_for("accounts.home"))

web/goalkeeper/notifications/routes.py
from flask import Blueprint, flash, url_for, redirect, render_template
from flask_login import login_user, login_required, current_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash
from goalkeeper.accounts.forms import LoginForm, RegisterForm
from goalkeeper.models import db, User, Friend, Notification, Goal
from flask import request
from goalkeeper.goals.forms import GoalForm
from sys import stderr
from sqlalchemy import or_
from datetime import datetime, timedelta

notifications = Blueprint("notifications", __name__, url_prefix="/notifications")


@notifications.route('/list_notifications', methods=['GET'])
@login_required
def list_notifications():
    # Return list of all notifications
    goals = Goal.query.filter(
        Goal.due_date is not None,
        Goal.due_date - datetime.now() < timedelta(days=3),
        Goal.due_date - datetime.now() >= timedelta(days=0)
    ).all()
    for goal in goals:
        t = goal.due_date - datetime.now()
        daystring = "tomorrow: " if t.days + 1 == 1 else "in " + str(t.days + 1) + " days: "
        notification = Notification(
            user_email=current_user.email,
            description="You have a goal coming up " + daystring + goal.title,
            link=url_for('goals.goal', goalid=goal.id)
        )
        db.session.add(notification)
    db.session.commit()
    notifications_query = Notification.query.filter(Notification.user_email == current_user.email)
    unread_notes = notifications_query.filter(Notification.clicked == False).all()
    return render_template("notifications.html", notifications_list=unread_notes)

web/goalkeeper/templates/add_goal.html
{% extends "base.html" %}

{% block content %}
{#{% for message in get_flashed_messages() %}#}
{#    <div class="flash">{{ message }}</div>#}
{#  {% endfor %}#}
    <div class="container justify-content-center">
        <div class="jumbotron">
            <h1>Add Goals</h1>
        </div>
        <form action="{{ url_for('goals.add_goal') }}" method="post">
                <div class="form-group">
                    <label for="formGroupExampleInput">Goal Name:</label>
                    {{ form.title(class_="form-control")}}
                    <label for="formGroupExampleInput">Goal Description:</label>
                    {{ form.description(class_="form-control") }}
                    <label for="formGroupExampleInput">Tags:</label>
                    {{ form.tags(class_="form-control") }}
                    <label for="formGroupExampleInput">Private:</label>
                    {{ form.private_goal(class_="form-control") }}
                    <div class="form-group row mt-3">
                        <div class="col-sm-10">
                          <button type="submit" class="btn btn-primary">Create Goal</button>
                        </div>
                    </div>
                    {{ form.csrf_token }}
                </div>
        </form>
    </div>
{% endblock %}

web/goalkeeper/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="{{url_for('static', filename='custom.css')}}" rel="stylesheet" type="text/css" />
        {% block extralinks %}{% endblock %}
        <title>{% block title %}{% endblock %} - Goal Keeper</title>
    {% endblock %}
</head>
<body>
{#    {% block navbar %} {{nav.account_nav.render()}} {% endblock %}#}
<div class="pos-f-t">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{{ url_for('accounts.home') }}">Goal Keeper</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('accounts.home') }}">Home </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('feed.home') }}">Feed </a>
          </li>
{#          <li class="nav-item">#}
{#            <a class="nav-link" href="{{ url_for('goals.add_goal') }}">Create Goals </a>#}
{#          </li>#}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('accounts.completed_goals') }}">View Completed Goals</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('accounts.view_calendar') }}">Calendar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('friends.list_friends') }}">Find Friends</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('forum.home') }}">Forums</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('notifications.list_notifications') }}">
                Notifications
{#                <span class="badge badge-light">4</span>#}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('accounts.logout') }}">Logout</a>
          </li>
        </ul>
      </div>
    </nav>
</div>
<div class="container">
  <div class="flash-container">
    <div class="flash">
      {% for message in get_flashed_messages() %}
        <div class="alert alert-info alert-dismissible fade show">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          {{ message }}
        </div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="content">
  {% block content %}{% endblock %}
</div>

<footer>
  <div class="text-center py-3">
    Goal Keeper: Created by UMD CMSC 435 Fall 2019 Team 3
  </div>
</footer>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>

web/goalkeeper/templates/calendar.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='calendar.css') }}" />
    <script src="{{ url_for('static', filename='calendar.js') }}" ></script>
{% endblock %}

{% block content %}
<div class="overlay" id="overlay">
    <form action="{{ url_for('goals.add_goal') }}" method="post" class="overlay_content">
        <h1>
            Add Goal
            <div style="color: black; display: inline-block; float: right; background-color: #ddd; padding: 5px;" onclick="off()">X</div>
        </h1>
        <p class="overlay_form_content">
            <p>Goal Name: {{ form.title(class_="form-control") }}</p>
            <p>Goal Description: {{ form.description(class_="form-control") }}</p>
            <p>Private: {{ form.private_goal(class_="form-control") }}</p>
            <p>Goal Date: <span id="goal_date"></span><input id="due_date" name="due_date" type="hidden"></p>
            <input class="btn btn-primary" type="submit" onclick="off()">
            {{ form.csrf_token }}
        </p>
    </form>
</div>
<div class="month">
    <ul>
        <li class="prev" onclick="decrementMonth()">&#10094;</li>
        <li class="next" onclick="incrementMonth()">&#10095;</li>
        <li>
            <span style="font-size:18px" id="monthText">

            </span>
            <br>
            <span style="font-size:18px" id="yearText">

            </span>
        </li>
    </ul>
</div>

<ul class="weekdays">
    <li>Sunday</li>
    <li>Monday</li>
    <li>Tuesday</li>
    <li>Wednesday</li>
    <li>Thursday</li>
    <li>Friday</li>
    <li>Saturday</li>
</ul>

<ul class="days" id="days"></ul>

<div id="debug">

</div>

<script type="text/javascript">
    setCalendar();
</script>
{% endblock %}

web/goalkeeper/templates/friends_list.html
{% extends "base.html" %}

{% block content %}
    <div class="container justify-content-center">
        <div class="jumbotron">
            <h1>Your Friends</h1>
        </div>
        {% if friends %}
        <ol class="list-group">
        {% for friend in friends %}
            <a href="{{ url_for('friends.view_profile', friendemail=friend.email) }}" class="list-group-item list-group-item-action ">
               <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ friend.username }}</h5>
                </div>
                <p>{{ friend.email }}</p>
            </a>
        {% endfor %}
        </ol>
        {% else %}
            <h5 class="mb-1">You have no friends yet :(</h5>
        {% endif %}

        <div class="jumbotron mt-4">
            <h1>Pending Friend Requests</h1>
        </div>
        {% if pending_receive %}
        <ol class="list-group">
        {% for friend in pending_receive %}
            <li class="list-group-item ">
               <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ friend.username }}</h5>
                </div>
                <p>{{ friend.email }}</p>
                <a class="btn btn-primary" href="{{ url_for('friends.add_friend', friendemail=friend.email) }}">Accept Friend Request!</a>
            </li>
        {% endfor %}
        </ol>
        {% else %}
            <h5 class="mb-1">You have no friend requests!</h5>
        {% endif %}

        <div class="jumbotron mt-4">
            <h1>Pending Sent Friend Requests</h1>
        </div>
        {% if pending_sent %}
        <ol class="list-group">
        {% for friend in pending_sent %}
            <li class="list-group-item ">
               <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ friend.username }}</h5>
                </div>
                <p>{{ friend.email }}</p>
                <button id="pending" class="btn btn-primary">Pending</button>
            </li>
        {% endfor %}
        </ol>
        {% else %}
            <h5 class="mb-1">You have no pending sent friend requests!</h5>
        {% endif %}

        <div class="jumbotron mt-4">
            <h1>Find Friends</h1>
        </div>
        <ol class="list-group">
        {% for friend in find_friends %}
            <li class="list-group-item ">
               <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ friend.username }}</h5>
                </div>
                <p>{{ friend.email }}</p>
                <a class="btn btn-primary" href="{{ url_for('friends.add_friend', friendemail=friend.email) }}">Add Friend!</a>
            </li>
        {% endfor %}
        </ol>


    </div>

{% endblock %}

web/goalkeeper/templates/register.html
<head>

     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


</head>

<body>

 <div class="container"><br>
      <center>
        <h2>Register</h2>
      </center>
    </div>

 <div class="container">
  <div class="flash-container">
    <div class="flash">
      {% for message in get_flashed_messages() %}
        <div class="alert alert-info alert-dismissible fade show">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          {{ message }}
        </div>
      {% endfor %}
    </div>
  </div>
</div>

    <div class=container"><br>
    <div class="row align-items-center justify-content-center">
    <div class="col-md-4">
      <form action="{{ url_for('accounts.register') }}" method="post">
        {{ form.csrf }}
        <div class="form-group">


            Username: {{ form.username(class_="form-control")}}


            <br>

	        Email: {{ form.email(class_="form-control") }}
	        <br>
	        Password: {{ form.password(class_="form-control") }}

	    </div>

            <input type="submit" value="Register" class="btn btn-primary"/>
            {{ form.csrf_token }}
      </form>
      <br>
        </div>
    <br>
    </div>
    </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

  </body>